package com.example.sarcopeniamonitor

import android.util.Log
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.snapshots.SnapshotStateList

data class PhysicalTest(
    val gripStrengthData: Double? = null,
    val gaitSpeedData:  Double? = null,
)
class PhysicalTestList() {
    private val _peList = mutableStateListOf<PhysicalTest>()
    val peList: SnapshotStateList<PhysicalTest> = _peList

    fun getList(): SnapshotStateList<PhysicalTest> {
        return peList
    }
    fun addElement(): PhysicalTest {
        val newRecord = PhysicalTest() // newID)
        // "autogenerated=True":  If you pass 0, Room will ignore it and generate a unique ID.
//        newID += 1
        _peList.add(newRecord)
        Log.d("Add a new record", newRecord.toString())
        return newRecord
    }

    fun getLastElement(): PhysicalTest? {
        if (_peList.size > 0) {
            return _peList.last()
        }
        return null
    }

    fun clear() {
        _peList.clear()
    }
    fun removeElement(record: PhysicalTest) {
        _peList.remove(record)  // Removes the specified record from the list
        Log.d("Remove a record", "Record removed.")
    }
}