# Generated by Django 5.1.7 on 2025-03-15 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecord',
            fields=[
                ('recordID', models.BigAutoField(primary_key=True, serialize=False)),
                ('recordDate', models.CharField(max_length=16)),
                ('recordTime', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('sbp', models.FloatField(blank=True, null=True)),
                ('dbp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
