# Generated by Django 5.1.7 on 2025-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gripStrengthData', models.FloatField(blank=True, null=True)),
                ('gaitSpeedData', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asmiPrediction', models.FloatField(blank=True, null=True)),
                ('handGripPrediction', models.FloatField(blank=True, null=True)),
                ('sarcopeniaStatus', models.IntegerField(blank=True, null=True)),
                ('gaitSpeedData', models.FloatField(blank=True, null=True)),
                ('standUpData', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('smoking', models.IntegerField(blank=True, null=True)),
                ('a2_1', models.IntegerField(blank=True, null=True)),
                ('a2_2', models.IntegerField(blank=True, null=True)),
                ('b1_2', models.IntegerField(blank=True, null=True)),
                ('b2_2', models.IntegerField(blank=True, null=True)),
                ('b9', models.IntegerField(blank=True, null=True)),
                ('c15', models.IntegerField(blank=True, null=True)),
                ('d1', models.IntegerField(blank=True, null=True)),
                ('d2', models.IntegerField(blank=True, null=True)),
                ('d3', models.IntegerField(blank=True, null=True)),
                ('e1', models.IntegerField(blank=True, null=True)),
                ('meal_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('recordID', models.BigAutoField(primary_key=True, serialize=False)),
                ('recordDate', models.CharField(max_length=16)),
                ('recordTime', models.CharField(max_length=16)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('sbp', models.FloatField(blank=True, null=True)),
                ('dbp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
