# Generated by Django 5.1.7 on 2025-03-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyRecord',
            new_name='UserRecord',
        ),
    ]
