# Generated by Django 5.1.7 on 2025-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userrecord_meal_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrecord",
            old_name="meal_images",
            new_name="mealImages",
        ),
        migrations.AddField(
            model_name="mealimage",
            name="meal_type",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
