# Generated by Django 5.1.7 on 2025-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_meal_type_mealimage_mealtype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealimage",
            old_name="uploadedAt",
            new_name="uploaded_at",
        ),
        migrations.RenameField(
            model_name="userrecord",
            old_name="mealImages",
            new_name="meal_images",
        ),
        migrations.RemoveField(
            model_name="mealimage",
            name="mealType",
        ),
    ]
