# Generated by Django 5.1.7 on 2025-04-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_meal_type_mealimage_mealtype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrecord",
            old_name="meal_images",
            new_name="mealImages",
        ),
    ]
