# Generated by Django 5.1.7 on 2025-04-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_meal_images_userrecord_mealimages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrecord",
            old_name="mealImages",
            new_name="meal_images",
        ),
    ]
