# Generated by Django 5.1.7 on 2025-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_mealimage_image_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrecord",
            name="meal_images",
        ),
        migrations.DeleteModel(
            name="MealImage",
        ),
        migrations.AddField(
            model_name="userrecord",
            name="meal_images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
