# Generated by Django 5.1.7 on 2025-04-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_userrecord_meal_images_delete_mealimage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrecord",
            old_name="meal_images",
            new_name="mealImages",
        ),
    ]
