# Generated by Django 5.1.7 on 2025-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mealimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='meal_images',
            field=models.ManyToManyField(blank=True, related_name='user_records', to='app.mealimage'),
        ),
    ]
