# Generated by Django 5.1.7 on 2025-04-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_mealimage_meal_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealimage",
            old_name="meal_type",
            new_name="mealType",
        ),
        migrations.RenameField(
            model_name="mealimage",
            old_name="uploaded_at",
            new_name="uploadedAt",
        ),
    ]
