# Generated by Django 5.1.7 on 2025-04-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_mealimages_userrecord_meal_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealimage",
            old_name="mealType",
            new_name="meal_type",
        ),
        migrations.RenameField(
            model_name="mealimage",
            old_name="uploadedAt",
            new_name="uploaded_at",
        ),
    ]
