# Generated by Django 5.1.7 on 2025-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_mealtype_mealimage_meal_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealimage",
            name="image_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
