# Generated by Django 5.1.7 on 2025-04-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_meal_images_userrecord_mealimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="meal_status",
        ),
    ]
